routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::group(['as' => 'home'], function() {
    Route::get('/', ['as' => 'index', 'uses' => 'HomeController@index']);
});

// Routes for administrator
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth']], function() {

    // Routes for brands
    Route::group(['prefix' => 'brands', 'as' => 'brands.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'ProductBrandsController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'ProductBrandsController@create']);
        Route::post('', ['as' => 'store', 'uses' => 'ProductBrandsController@store']);
        Route::get('{brand}/edit', ['as' => 'edit', 'uses' => 'ProductBrandsController@edit']);
        Route::put('{brand}', ['as' => 'update', 'uses' => 'ProductBrandsController@update']);
    });

    // Routes for categories
    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'ProductCategoriesController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'ProductCategoriesController@create']);
        Route::post('', ['as' => 'store', 'uses' => 'ProductCategoriesController@store']);
        Route::get('{category}/edit', ['as' => 'edit', 'uses' => 'ProductCategoriesController@edit']);
        Route::put('{category}', ['as' => 'update', 'uses' => 'ProductCategoriesController@update']);
    });

    // Routes for roles
    Route::group(['prefix' => 'roles', 'as' => 'roles.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'RolesController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'RolesController@create']);
        Route::post('', ['as' => 'store', 'uses' => 'RolesController@store']);
        Route::get('{role}/edit', ['as' => 'edit', 'uses' => 'RolesController@edit']);
        Route::put('{role}', ['as' => 'update', 'uses' => 'RolesController@update']);
    });
});

resources/views/admin/brands/includes/_create.blade.php
<form action="{{ $brand->exists ? route('admin.brands.update', ['brand' => $brand]) : route('admin.brands.store') }}" method="post">
    {{csrf_field()}}
    @if ($brand->exists)
        <input type="hidden" name="_method" value="put">
    @endif
    <div class="col-xs-12 col-sm-6">
        <div class="form-group required">
            <label for="BrandName">Brand Name <sup>*</sup> </label>
            <input required="" type="text" value="{{ old('name', $brand->name) }}"class="form-control" name="name" placeholder="Brand Name">
        </div>
    </div>
    <div class="col-lg-12">
        <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> &nbsp; Save</button>
    </div>
</form>