routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::group(['as' => 'home'], function() {
    Route::get('/', ['as' => 'index', 'uses' => 'HomeController@index']);
});

// Routes for administrator
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth']], function() {

    // Routes for brands
    Route::group(['prefix' => 'brands', 'as' => 'brands.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'ProductBrandsController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'ProductBrandsController@create']);
        Route::post('', ['as' => 'store', 'uses' => 'ProductBrandsController@store']);
        Route::get('{brand}/edit', ['as' => 'edit', 'uses' => 'ProductBrandsController@edit']);
        Route::put('{brand}', ['as' => 'update', 'uses' => 'ProductBrandsController@update']);
    });

    // Routes for categories
    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'ProductCategoriesController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'ProductCategoriesController@create']);
        Route::post('', ['as' => 'store', 'uses' => 'ProductCategoriesController@store']);
        Route::get('{category}/edit', ['as' => 'edit', 'uses' => 'ProductCategoriesController@edit']);
        Route::put('{category}', ['as' => 'update', 'uses' => 'ProductCategoriesController@update']);
    });

    // Routes for roles
    Route::group(['prefix' => 'roles', 'as' => 'roles.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'RolesController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'RolesController@create']);
        Route::post('', ['as' => 'store', 'uses' => 'RolesController@store']);
        Route::get('{role}/edit', ['as' => 'edit', 'uses' => 'RolesController@edit']);
        Route::put('{role}', ['as' => 'update', 'uses' => 'RolesController@update']);
    });
});

resources/views/admin/categories/create.blade.php
@extends('layouts.master')
@section('content')
    <div class="container main-container headerOffset">
        {!! $category->exists ? Breadcrumbs::render('edit-category', $category) : Breadcrumbs::render('create-category') !!}
        @include('flash::message')
        <div class="row">
            <div class="col-lg-9 col-md-9 col-sm-7">
                <h1 class="section-title-inner"> {{ $category->exists ? 'Edit Category':'Add New Category' }}</h1>
                <div class="row userInfo">
                    <div class="col-lg-12">
                        <p class="required"><sup>*</sup> Required field</p>
                    </div>
                    @include('admin.categories.includes._create')
                    <div class="col-lg-12 clearfix">
                        <ul class="pager">
                            <li class="previous pull-right"><a href="index.html"> <i class="fa fa-home"></i> Go to Shop </a>
                            </li>
                            <li class="next pull-left"><a href="account.html"> ← Back to My Account</a></li>
                        </ul>
                    </div>
                </div>

            </div>
            <div class="col-lg-3 col-md-3 col-sm-5"></div>
        </div>

        <div style="clear:both"></div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.master')
@section('content')
    <div class="container main-container headerOffset">
        {!! Breadcrumbs::render('categories') !!}
        @include('flash::message')
        <div class="row">
            <div class="col-lg-9 col-md-9 col-sm-7">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-6">
                            <h1 class="section-title-inner">List of Categories</h1>
                        </div>
                        <div class="col-md-6">
                            <a href="{{ route('admin.categories.create') }}" class="btn btn-primary pull-right">Add Category</a>
                        </div>
                    </div>
                </div>
                @if($categories->count())
                    <div class="col-lg-12 col-md-12 col-sm 12">

                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Parent</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($categories as $category)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $category->name }}</td>
                                        <td>{{ $category->parentCategory->name ?? '_'}}</td>
                                        <td>
                                            <a href="{{route('admin.categories.edit', ['category' => $category])}}" class="btn btn-inline btn-success btn-sm">
                                                <i class="fa fa-pencil"></i> Edit
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                @else
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <h3 class="text-center">
                                        No Category added
                                    </h3>
                                    <p class="text-center">
                                        <a class="btn btn-primary" type="button" href="{{ route('admin.categories.create') }}">Add New Category</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                @endif
            </div>
            <div class="col-lg-3 col-md-3 col-sm-5"></div>
        </div>

        <div style="clear:both"></div>
    </div>
@endsection

resources/views/admin/categories/show.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: ntimyeboah
 * Date: 28/05/2017
 * Time: 3:29 PM
 */